language: node_js
node_js:
- '9'
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_8a2e9576d3d0_key -iv $encrypted_8a2e9576d3d0_iv
  -in used-books-deploy.enc -out ~/.ssh/used-books-deploy -d
- chmod 600 ~/.ssh/used-books-deploy